import type { Metadata } from "next";
import { Space_Grotesk, Tektur } from "next/font/google";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const tektur = Tektur({
  variable: "--font-tektur",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TECH3",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${spaceGrotesk.variable} ${tektur.variable}`}
    >
      <body className='bg-background text-foreground antialiased'>
        {children}
      </body>
    </html>
  );
}
